version: "3.7"

services:
  db:
    image: 'postgres:14.2'
    ports:
      - "5436:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-db:/var/lib/postgresql/data/
  frontend:
    depends_on:
      - db
    build:
      context: "./front-end"
    restart: always
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1
  broker-service:
    depends_on:
        - db
    build:
      context: "./broker-service"
    restart: always
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
  auth-service:
    depends_on:
        - db
    build:
      context: "./auth-service"
    restart: always
    ports:
      - "3001:3001"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DATABASE_URL: postgres://postgres:secret@db:5432/postgres?sslmode=disable

volumes:
  postgres-db:
    driver: local