apiVersion: v1
kind: Service
metadata:
  name: email-srv
spec:
  selector:
    module-name: email-module
  # type: LoadBalancer
  ports:
  - port: 3003
    name: http
    targetPort: 3003
    protocol: TCP
  - port: 9000
    name: g-rpc
    targetPort: 9000
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      module-name: email-module
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        module-name: email-module
    spec:
      containers:
      - image: go_microservices-email-service:latest
        name: email-image
        # Testing with locally build images
        imagePullPolicy: Never
        securityContext:
          runAsUser: 1001
          runAsNonRoot: true
        ports:
          - containerPort: 3003
            protocol: TCP
          - containerPort: 9000
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /ping
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
           limits:
              cpu: 200m
              memory: 150Mi
           requests:
              cpu: 100m
              memory: 100Mi
        env:
          - name: FROM_ADDR
            valueFrom:
              secretKeyRef:
                  name: email-secret
                  key: FROM_ADDR
          - name: FROM_NAME
            valueFrom:
              secretKeyRef:
                  name: email-secret
                  key: FROM_NAME
          - name: ENCRYTION
            valueFrom:
              secretKeyRef:
                  name: email-secret
                  key: ENCRYTION
          - name: MAIL_DOMAIN
            valueFrom:
              secretKeyRef:
                  name: email-secret
                  key: MAIL_DOMAIN
          - name: MAIL_HOST
            valueFrom:
              secretKeyRef:
                  name: email-secret
                  key: MAIL_HOST
          - name: MAIL_PORT
            valueFrom:
              secretKeyRef:
                  name: email-secret
                  key: MAIL_PORT
          - name: MAIL_USERNAME
            valueFrom:
              secretKeyRef:
                  name: email-secret
                  key: MAIL_USERNAME
          - name: MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: email-secret
                  key: MAIL_PASSWORD
