apiVersion: v1
kind: Service
metadata:
  name: logger-srv
spec:
  selector:
    module-name: logger-module
  # type: LoadBalancer
  ports:
  - port: 3002
    name: http
    targetPort: 3002
    protocol: TCP
  - port: 5000
    name: rpc
    targetPort: 5000
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      module-name: logger-module
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        module-name: logger-module
    spec:
      containers:
      - image: go_microservices-logger-service:latest
        name: logger-image
        # Testing with locally build images
        imagePullPolicy: Never
        securityContext:
          runAsUser: 1001
          runAsNonRoot: true
        ports:
          - containerPort: 3002
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /ping
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
           limits:
              cpu: 200m
              memory: 150Mi
           requests:
              cpu: 100m
              memory: 100Mi
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                  name: logger-secret
                  key: MONGO_URL
