apiVersion: v1
kind: Service
metadata:
  name: mailhog-srv
spec:
  selector:
    module-name: mailhog-module
  # type: LoadBalancer
  ports:
  - port: 1025
    name: smtp
    targetPort: 1025
    protocol: TCP
  - port: 8025
    name: ui
    targetPort: 8025
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      module-name: mailhog-module
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        module-name: mailhog-module
    spec:
      containers:
      - image: mailhog/mailhog
        name: mailhog
        imagePullPolicy: Always
        ports:
          - containerPort: 1025
            protocol: TCP
          - containerPort: 8025
            protocol: TCP
        resources:
           limits:
              cpu: 200m
              memory: 150Mi
           requests:
              cpu: 100m
              memory: 100Mi