# This Manifest is used to simplify testing in development
# In Production the RabbitMQ Cluster Operator should be used - whicih is an overkill for the current purpouses

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-srv
spec:
    # Headless service - that exposes each stateful pod(saparate db instance) individualy
  clusterIP: None
  ports:
    - port: 5672
      name: amqp
      targetPort: 5672
    - port: 15672
      name: ui
      targetPort: 15672
  # type: NodePort
  selector:
    role: rabbitmq

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      role: rabbitmq
  serviceName: rabbitmq-srv
  template:
    metadata:
      labels:
        role: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        imagePullPolicy: Always
        ports:
          - containerPort: 5672
          - containerPort: 15672
        volumeMounts:
          - name: rabbitmq-persistent-storage
            mountPath: /var/lib/rabbitmq/
  
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 0.5Gi